/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.PaqueteDocumentacion;
import io.swagger.model.RequestDocumento;
import io.swagger.model.RequestPedirDocumentos;
import io.swagger.model.ResponseDocumento;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-09-15T21:09:20.478863961Z[GMT]")
@Validated
public interface DocumentoApi {

    @Operation(summary = "Descargar documento a la carpeta ciudadana", description = "", tags={ "Documento" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Descarga a la carpeta exitosa", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDocumento.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/documento/descargar/{idCarpeta}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseDocumento> documentoDescargarIdCarpetaPost(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("idCarpeta") String idCarpeta);


    @Operation(summary = "Enviar documento a la entidad que lo requiere", description = "", tags={ "Documento" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Documento enviado a la entidad", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDocumento.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/documento/enviar",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseDocumento> documentoEnviarPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody RequestDocumento body);


    @Operation(summary = "Pedir documentos", description = "", tags={ "Ciudadano" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Solicitud de documentos emitidos a la entidad", content = @Content(mediaType = "application/json", schema = @Schema(implementation = PaqueteDocumentacion.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/documento/solicitar",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<PaqueteDocumentacion> documentoSolicitarPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody RequestPedirDocumentos body);

}

