/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Operador;
import io.swagger.model.Registraduria;
import io.swagger.model.RequestOperadorCiudadano;
import io.swagger.model.ResponseOperadorCiudadano;
import io.swagger.model.ResponseRegistraduria;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-09-15T21:09:20.478863961Z[GMT]")
@Validated
public interface OperadorApi {

    @Operation(summary = "Agregar Operador", description = "", tags={ "GovCentral" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Operador agregado exitosamente", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Operador.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/operador/agregar",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Operador> operadorAgregarPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Operador body);


    @Operation(summary = "Asociar el ciudadano con el Operador", description = "", tags={ "GovCentral" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Asociación del operador y ciudadano exitosa", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseOperadorCiudadano.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/operador/asociar",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseOperadorCiudadano> operadorAsociarPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody RequestOperadorCiudadano body);


    @Operation(summary = "Consultar el operador al cual se encuentra asociado el usuario", description = "", tags={ "GovCentral" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Consulta del operador exitosa", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Operador.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/operador/consultar/{tipoId}/{identificacion}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Operador> operadorConsultarTipoIdIdentificacionGet(@Parameter(in = ParameterIn.PATH, description = "Tipo de identificación del usuario a consultar", required=true, schema=@Schema()) @PathVariable("tipoId") String tipoId, @Parameter(in = ParameterIn.PATH, description = "Identificación del usuario a consultar", required=true, schema=@Schema()) @PathVariable("identificacion") String identificacion);


    @Operation(summary = "Verificación del ciudadano ante registraduria", description = "", tags={ "GovCentral" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Usuario evaluado exitosamente", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseRegistraduria.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/operador/verificar/registraduria",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseRegistraduria> operadorVerificarRegistraduriaPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Registraduria body);

}

